In [1]:
from sklearn.datasets import load_digits


data = load_digits()
data.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns


sns.set()
n_of_test_plots = 4

for nth_plot in range(1, n_of_test_plots + 1):
    plt.subplot(100 + 10 * n_of_test_plots + nth_plot)
    plt.imshow( - data.data[nth_plot - 1].reshape(8, 8), cmap='gray');
    plt.xticks(());
    plt.yticks(());
    plt.title('An image of: ' + str(data.target[nth_plot - 1]))

In [3]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split


scaler = MinMaxScaler()
class_encoder = OneHotEncoder(categories='auto')

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=.1)

In [4]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

y_train_encoded = class_encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
y_test_encoded = class_encoder.transform(y_test.reshape(-1, 1)).toarray()

C:\Users\kondorm\AppData\Roaming\Python\Python37\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [5]:
X_train[0], y_train_encoded[0]

(array([ 0.,  0.,  6., 16., 16.,  7.,  0.,  0.,  0.,  0., 13., 12., 15.,
        10.,  0.,  0.,  0.,  0.,  3.,  6., 13.,  9.,  0.,  0.,  0.,  0.,
         8., 16., 16., 15.,  6.,  0.,  0.,  0.,  1.,  9., 14.,  8.,  5.,
         0.,  0.,  0.,  0., 11.,  9.,  0.,  0.,  0.,  0.,  0.,  4., 16.,
         3.,  0.,  0.,  0.,  0.,  0., 10., 10.,  0.,  0.,  0.,  0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]))

In [42]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score


mlp = MLPClassifier(
    learning_rate_init=0.05,
    max_iter=175,
    hidden_layer_sizes=[100],
    alpha=0.01,
    random_state=0
)

print('Training model ...')
mlp.fit(X_train_scaled, y_train_encoded)

print('Score on train:', mlp.score(X_train_scaled, y_train_encoded))
print('Score on test:', mlp.score(X_test_scaled, y_test_encoded))
print()
print('Cross Selection score on train:', np.mean(cross_val_score(mlp, X_train_scaled, y_train_encoded, cv=3)))
print('Cross Selection score on test:', np.mean(cross_val_score(mlp, X_test_scaled, y_test_encoded, cv=3)))
print()
print(mlp)

Training model ...


Score on train: 1.0
Score on test: 0.9777777777777777



Cross Selection score on train: 0.9523809523809524


Cross Selection score on test: 0.8111111111111112

MLPClassifier(activation='relu', alpha=0.01, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=[100], learning_rate='constant',
       learning_rate_init=0.05, max_iter=175, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=0, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
